version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Ho_Chi_Minh
    labels: [dependencies, github-actions]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:15"
      timezone: Asia/Ho_Chi_Minh
    labels: [dependencies, docker]
